version: '3.8'

services:
  app:
    build: .
    container_name: diag_gen_app
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ollama:
    image: ollama/ollama:latest
    container_name: diag_gen_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # If you don't have NVIDIA GPU, comment out the deploy section above

volumes:
  ollama_data:
